### ISSUE TITLE
CCSDS image data compression module

### ISSUE THREAD

**Issue by ryanpdx** [oresat/oresat-linux-app-framework#16]
Since 3 of 5 OreSat Linux cards are camera cards, we should have a common image compression module.

CCSDS has a [Image Data Compression Blue Book](https://public.ccsds.org/Pubs/122x0b2.pdf)

It would be great to find a C, C++, or Rust library that implement this standard, that could be binded to Python and include in this framework (a pure Python module may be too slow).

**Comment by ryanpdx** [comment]
C: http://hyperspectral.unl.edu/index.html

**Comment by ryanpdx** [comment]
Java: http://www.gici.uab.cat/TER/

**Comment by kk60503** [comment]
I've attempted to push my current progress under a /bpe repo within /olaf. I've begun the Python binding (binding.cpp) in earnest, but all of the other code should function properly.

**Comment by ryanpdx** [comment]
This was moved to it's own repo: oresat/libbpe
