### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by ryanpdx** [oresat/oresat-linux-app-framework#3]
Need to go crazy with unit tests.

Has unit tests:

- General
  - [ ] App
  - [x] Updater
- Common
  - [x] ECSS time functions
  - [x] OreSatFile
  - [x] OreSatFileCache
  - [x] PRU (requires hardware)
- Resources
  - [x] ECSSResource
  - [x] OSResource
  - [x] FwriteResource
  - [x] FreadResource
  - [x] FileCacheResource
  - [ ] LogsResource
  - [x] SysInfoResource
  - [ ] UpdaterResource

**Comment by ryanpdx** [comment]
I am working on the updater unit tests

**Comment by dan-trang** [comment]
I am currently working on the OreSatFileCache unit test

**Comment by ryanpdx** [comment]
This is basically done. We will always be adding more unit tests.
